sonar.projectKey=dndudchl_a2-back
sonar.organization=dndudchl

# Source code locations
sonar.sources=.

# Coverage report paths
sonar.python.coverage.reportPaths=coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8

# Additional properties
sonar.python.version=3.10
